libraries:              # Library mappings must have a colon (:) placed after them
  Movies:
    collection_files:
    - file: config/custom/Movies.yml
    - file: config/custom/holiday.yml
    - file: config/custom/tautulli.yml
    - file: config/custom/moviestudios.yml
    - file: config/custom/moviecharts.yml
    - file: config/custom/moviecollectionsalpha.yml
    - file: config/custom/moviesmartcollections.yml
    metadata_files:
    - folder: config/custom/metadata/movies
    settings:
      asset_directory: config/assets/movies
  TV Shows:
    asset_directory: config/assets/TV
    metadata_files:
    - folder: config/custom/metadata/tv
    collection_files:
    - file: config/custom/TV.yml
    - file: config/custom/tvcollections.yml
    settings:                  # Can be individually specified per library as well
      asset_directory: config/assets/tv
settings:                  # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: true
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: false
  create_asset_folders: true
  collection_minimum: 1
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  asset_depth: 0
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  default_collection_order:
  item_refresh_delay: 0
  delete_not_scheduled: false
  only_filter_missing: false
  show_unconfigured: true
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: false
  playlist_exclude_users:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
plex:                       # Can be individually specified per library as well
  url:
  token:
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache:
  verify_ssl:
tmdb:
  apikey: 
  language: en
  cache_expiration: 60
  region:
tautulli:                   # Can be individually specified per library as well
  url:
  apikey:
trakt:
  client_id: 
  client_secret: 
  pin:
  authorization:
    access_token: 
    token_type: Bearer
    expires_in: 
    refresh_token: 
    scope: public
    created_at: 
